[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lasso_prior"
version = "0.1.0"
description = "TabPFN-based feature selection with lasso prior"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "torch",
    "scikit-learn",
    "pyyaml",
    "tqdm",
    "tabpfn>=6.0.6",
    "wandb>=0.23.0",
    "tabicl>=0.1.4",
    "pyarrow>=22.0.0",
    "h5py>=3.15.1",
]

[tool.setuptools.packages.find]
where = ["src"]
